apiVersion: v1
kind: Pod
metadata:
  name: sk8r
  labels:
    spark-app-selector: sk8r
spec:
  containers:
    - name: sk8r
      securityContext:
        runAsUser: 0
      image: hareendranvr/driver
      ports:
        - containerPort: 37771
      resources:
        requests:
          cpu: "2"
          memory: "8Gi"
        limits:
          cpu: "4"
          memory: "8Gi"
  serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
    name: sk8r
spec:
    clusterIP: "None"
    selector:
        spark-app-selector: sk8r
    ports:
        - name: spark-driver-port
          protocol: TCP 
          port: 2222
          targetPort: 2222
        - name: blockmanager
          protocol: TCP 
          port: 7777
          targetPort: 7777