apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Spark&Docker\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: notsparkmaster
  name: notsparkmaster
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "7077"
      port: 7077
      targetPort: 7077
  selector:
    io.kompose.service: notsparkmaster
status:
  loadBalancer: {}
