apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Spark&Docker\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Spark&Docker\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
        - image: hareendranvr/notsparkmaster
          name: spark-master
          ports:
            - containerPort: 8080
            - containerPort: 7077
          resources: {}
          volumeMounts:
            - mountPath: /opt/workspace
              name: shared-workspace
      restartPolicy: Always
      volumes:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: shared-workspace
status: {}
