apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Spark&Docker\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker-1
  name: spark-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-worker-1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Spark&Docker\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: spark-worker-1
    spec:
      containers:
        - env:
            - name: SPARK_WORKER_CORES
              value: "1"
            - name: SPARK_WORKER_MEMORY
              value: 512m
          image: hareendranvr/spark-worker
          name: spark-worker-1
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /opt/workspace
              name: shared-workspace
      restartPolicy: Always
      volumes:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: shared-workspace
status: {}
