apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Spark&Docker\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker-1
  name: spark-worker-1
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8081
  selector:
    io.kompose.service: spark-worker-1
status:
  loadBalancer: {}
