apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: deployments-services
deploy:
  kubectl:
    manifests:
    - shared-workspace-persistentvolumeclaim.yaml
    - spark-pod-service.yaml
    - spark-pod.yaml
