apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-pod
  labels:
    app: spark-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-pod
  template:
    metadata:
      labels:
        app: spark-pod
    spec:
      containers:
        - image: hareendranvr/spark-master
          name: spark-master
          env:
            - name: SPARK_CLUSTER_URL
              value: spark://192.168.1.36:7077
            - name: SPARK_MASTER_HOST
              value: 192.168.1.36
            - name : SPARK_MASTER_PORT
              value: "7077"
          ports:
            - containerPort: 8080
            - containerPort: 7077
          resources: {}
          volumeMounts:
            - mountPath: /opt/workspace
              name: shared-workspace
      restartPolicy: Always
      volumes:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: shared-workspace
status: {}
          
