apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
  labels:
    app.kubernetes.io/name: connect
    app.kubernetes.io/instance: connect
    app.kubernetes.io/version: 0.0.4
    app.kubernetes.io/managed-by: kubernetes-standalone-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver
  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:            
        - name: driver
          image: hareendranvr/spark-driver
          resources: {}
          env:
            - name: SPARK_DRIVER_URL
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

                
